export const blog = [
  {
    image: "/img/card1.jpg",
    title: "Estilo y Elegancia.",
    date: "11 junio, 2024",
    user: "Mariana Trujillo",
    slug: "estilo-elegancia",
  },
  {
    image: "/img/card2.jpg",
    title: "Espejo de Belleza.",
    date: "11 junio, 2024",
    user: "Mariana Trujillo",
    slug: "espejo-belleza",
  },
  {
    image: "/img/card3.jpg",
    title: "Belleza Natural.",
    date: "11 junio, 2024",
    user: "Mariana Trujillo",
    slug: "belleza-natural",
  },
  {
    image: "/img/card4.jpg",
    title: "Secretos de Belleza.",
    date: "11 junio, 2024",
    user: "Mariana Trujillo",
    slug: "secretos-belleza",
  },
  {
    image: "/img/card5.jpg",
    title: "Brillo Natural.",
    date: "11 junio, 2024",
    user: "Mariana Trujillo",
    slug: "brillo-natural",
  },
  {
    image: "/img/card6.jpg",
    title: "Rutina Básica.",
    date: "11 junio, 2024",
    user: "Mariana Trujillo",
    slug: "rutina-basica",
  },
  {
    image: "/img/card7.jpg",
    title: "Adiós, Acné.",
    date: "11 junio, 2024",
    user: "Mariana Trujillo",
    slug: "adios-acne",
  },
  {
    image: "/img/card8.jpg",
    title: "Hidratación 24/7.",
    date: "11 junio, 2024",
    user: "Mariana Trujillo",
    slug: "hidratacion-24/7",
  },
  {
    image: "/img/card9.jpg",
    title: "Ácido Hialurónico.",
    date: "11 junio, 2024",
    user: "Mariana Trujillo",
    slug: "acido-hialuronico",
  },
  {
    image: "/img/card10.jpg",
    title: "Protección Solar.",
    date: "11 junio, 2024",
    user: "Mariana Trujillo",
    slug: "proteccion-solar",
  },
  {
    image: "/img/card11.jpg",
    title: "Exfoliación Fácial.",
    date: "11 junio, 2024",
    user: "Mariana Trujillo",
    slug: "exfoliante-facial",
  },
];
